project:
  type: book
  output-dir: ../_site/notes

book:
  title: "Mécanique Quantique"
  subtitle: "Support de cours — PHYS301"

  navbar:
    right:
      - text: "**mécanique quantique**"
        href: https://antoineboulet.github.io/phys301-mecanique-quantique/

  chapters:
    - index.qmd
    - chapters/01-postulats.qmd
    - chapters/02-systemes-simples.qmd
    - chapters/03-moment-cinetique.qmd
    - chapters/04-perturbations.qmd
    - chapters/references.qmd

bibliography: references.bib



metadata-files:
  - system/fragments/default-header.yml
  - system/fragments/default-theme.yml
  - system/fragments/default-book.yml

  - system/fragments/book-header.yml
  - system/fragments/book-theme.yml
  - system/fragments/book-website.yml

  - system/fragments/main-navbar-fr.yml
  
  - system/fragments/lang-fr.yml

  - system/fragments/latex-book.yml
