project:
  type: website
  output-dir: ../_site

thanks: "ECUE: 6.2.1 : Mécanique Quantique — CI A3 FISE ISMANS 2025-2026"



website:
  navbar:
    right:
      - text: "**mécanique quantique**"
        href: https://antoineboulet.github.io/phys301-mecanique-quantique/

  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - text: "Notes de cours"
        href: https://antoineboulet.github.io/ 
      - section: "Diaporamas"
        contents:
          - ressources/cm/chap1.qmd
          - ressources/cm/chap2.qmd
      - section: "Travaux dirigés"
        contents:
          - section: "TD 1 · Fonction d'onde dans un potentiel"
            contents:
              - text: Énoncé
                href: ressources/td/01-fonction-d-onde-dans-un-potentiel/enonce.qmd
              - text: Correction
                href: ressources/td/01-fonction-d-onde-dans-un-potentiel/correction.qmd
      - section: "Notebooks"
        contents: 
          - ressources/nb/index.qmd
          - ressources/nb/tp1.ipynb






metadata-files:
  - system/fragments/default-header.yml
  - system/fragments/default-theme.yml
  - system/fragments/default-website.yml

  - system/fragments/page-header.yml
  - system/fragments/page-theme.yml
  - system/fragments/page-website.yml

  - system/fragments/main-navbar-fr.yml
  
  - system/fragments/lang-fr.yml
