project:
  type: website
  output-dir: ../_site

lang: fr

website:
  navbar:
    right:
      - text: "**mécanique quantique**"
        href: https://antoineboulet.github.io/phys301-mecanique-quantique/

  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - text: "Notes de cours"
        href: https://antoineboulet.github.io/ 
      - section: "Diaporamas"
        contents:
          - diaporamas/chap1.qmd
          - diaporamas/chap2.qmd
      - section: "Travaux dirigés"
        contents:
          - travaux-diriges/td1/td1-enonce.qmd
          - travaux-diriges/td2.qmd
      - section: "Notebooks"
        contents: 
          - notebooks/index.qmd
          - notebooks/tp1.ipynb

filters:
  - update-system/margin-html-figure.lua

metadata-files:
  - system/fragments/default-header.yml
  - system/fragments/default-theme.yml
  - system/fragments/default-website.yml
  - system/fragments/page-header.yml
  - system/fragments/page-theme.yml
  - system/fragments/page-website.yml
  - system/fragments/main-navbar-fr.yml
  - system/fragments/lang-fr.yml
