project:
  type: website
  output-dir: ../_site

thanks: "ECUE: 6.3.2 : Mécanique Quantique — CI ISMANS A3 FISE"

website:
  navbar:
    right:
      - text: "**mécanique quantique**"
        href: https://antoineboulet.github.io/phys301-mecanique-quantique/

  sidebar:
    contents:
      - text: "Notes de cours"
        href: https://antoineboulet.github.io/ 
      - section: "Diaporamas"
        contents:
          - ressources/cm/chap1.qmd
          - ressources/cm/chap2.qmd
      - section: "Travaux dirigés"
        contents:
          - section: "TD 1 · Fonction d'onde dans un potentiel"
            contents:
              - text: Énoncé
                href: ressources/td/01-fonction-d-onde-dans-un-potentiel/enonce.qmd
              - text: Correction
                href: ressources/td/01-fonction-d-onde-dans-un-potentiel/correction.qmd
      - section: "Notebooks"
        contents: 
          - ressources/nb/index.qmd
          - ressources/nb/tp1.ipynb

metadata-files:
  - system/fragments/default.yml
  - system/fragments/pages.yml  
  - system/fragments/lang-fr.yml