format:
  pdf:
    documentclass: article
    keep-tex: true
    pdf-engine: lualatex
    mainfont: "STIX Two Text"
    mathfont: "STIX Two Math"
    fontsize: 11pt
    fig-cap-location: bottom
    tbl-cap-location: top
    date: last-modified
    date-format: "D MMMM YYYY"
    author: Antoine Boulet